### ISSUE TITLE
MDE fails to start

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#127]
My PC with Win10 behaved weirdly so I hard-rebooted it while MDE was open (amongst other applications). After the PC booted up again, I could not start MDE. I tried uninstalling and reinstalling it, also my APPDATA files look untouched but the app just won't start.

Here is what I found in Event Viewer's application log:

Event 1000, Application Error:
```
Faulting application name: mde.exe, version: 1.24.0.0, time stamp: 0x56c86ff4
Faulting module name: KERNELBASE.dll, version: 10.0.10586.162, time stamp: 0x56cd45b4
Exception code: 0xe0434352
Fault offset: 0x0000000000071f28
Faulting process id: 0x197c
Faulting application start time: 0x01d17a6043e0648d
Faulting application path: C:\Users\borek\AppData\Local\MarkdownEdit\bin\mde.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report Id: 91255417-f5d1-4740-9a1e-e3e188b24c8d
Faulting package full name: 
Faulting package-relative application ID: 
```

Event 1026, .NET Runtime:

```
Application: mde.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at MarkdownEdit.Properties.Settings.get_UpgradeSettings()
   at MarkdownEdit.App.InitializeSettings()
   at MarkdownEdit.App.OnStartup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at MarkdownEdit.App.Main()

```

Any ideas?

**Comment by borekb** [comment]
Found another log, this time only with the "info" severity but might be useful as well:

```
Fault bucket 129040095620, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: mde.exe
P2: 1.24.0.0
P3: 56c86ff4
P4: System.Xml
P5: 4.6.1064.2
P6: 565f9c84
P7: b79
P8: 27
P9: IOIBMURHYNRXKW0ZXKYRVFN0BOYYUFOW
P10: 

Attached files:
C:\Users\borek\AppData\Local\Temp\WERBFE9.tmp.WERInternalMetadata.xml
C:\Windows\Temp\WERC596.tmp.csv
C:\Users\borek\AppData\Local\Temp\WERC5B6.tmp.appcompat.txt
C:\ProgramData\Microsoft\Windows\WER\Temp\WERC5D6.tmp.dmp
C:\Users\borek\AppData\Local\Temp\WERC962.tmp.WERDataCollectionFailure.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_mde.exe_eb1bd76e7ea11052183e1e87bff537a36183c7_9d78c982_1e05c95f

Analysis symbol: 
Rechecking for solution: 0
Report Id: 91255417-f5d1-4740-9a1e-e3e188b24c8d
Report Status: 4104
Hashed bucket: a6f8d6dcb7889ba8bb1aba715ea92c05
```

**Comment by mike-ward** [comment]
The call stack indicates the XML setting file is corrupted.

In your User/App_Data/Local/MarkdownEdit folder you'll see some folders like:

`mde.exe_Url_htckrcqzc5ek51ufz1skdztxdivvc020`

Delete them.

**Comment by borekb** [comment]
Ah I was only looking into the `../Roaming/..` folder. Thanks!

**Comment by borekb** [comment]
(BTW I really suffered without MDE, editing Markdown in text editors like Sublime Text or VS Code just sucks for some reason.)

**Comment by mike-ward** [comment]
I need to wrap this code in an exception handler.
