### ISSUE TITLE
MDE crashes when attempting to scroll the source text with mouse wheel

### ISSUE THREAD

**Issue by guban** [mike-ward/Markdown-Edit#146]
Using MDE version 1.26 on Windows 7 64bit.

Steps:

1. Start MDE. No need to open a file.
2. Place mouse within the source text (not preview).
3. Rotate mouse wheel.

Actual result: MDE crashes.
Expected result: MDE should not crash.

Error details:

    Problem signature:
      Problem Event Name:	CLR20r3
      Problem Signature 01:	mde.exe
      Problem Signature 02:	1.26.0.0
      Problem Signature 03:	571d1a85
      Problem Signature 04:	WpfMouseWheelLib
      Problem Signature 05:	1.0.0.0
      Problem Signature 06:	4e16c6ca
      Problem Signature 07:	322
      Problem Signature 08:	f
      Problem Signature 09:	System.ArgumentOutOfRange
      OS Version:	6.1.7601.2.1.0.256.4
      Locale ID:	4105
      Additional Information 1:	62d4
      Additional Information 2:	62d49b8f1d80536cd7a29b4ccd80b952
      Additional Information 3:	22bf
      Additional Information 4:	22bf286c4a6194a5f611fc1da6dde415

**Comment by mike-ward** [comment]
Can anyone reproduce this? I can't.

**Comment by punker76** [comment]
@mike-ward latest mde works on my win 7 64 bit machine ™

**Comment by guban** [comment]
It looks like the problem was caused by an old version of Logitech Gaming Software. After updating it, I can't reproduce the problem anymore. For reference, below is the exception that was reported by Visual Studio debugger before the update:

    System.ArgumentOutOfRangeException was unhandled
      HResult=-2146233086
      Message=Specified argument was out of the range of valid values.
    Parameter name: timeStamp
      ParamName=timeStamp
      Source=WpfMouseWheelLib
      StackTrace:
           at Logitech.Windows.MotionFlow.NativeMotionSource.UpdateTimings(Int64 timeStamp)
           at Logitech.Windows.MotionFlow.NativeMotionSource.PreTransmit(Int32 timeStamp, Int32 nativeDelta)
           at Logitech.Windows.Input.MouseWheel.PreTransmit(Int32 timeStamp, Int32 nativeDelta)
           at Logitech.Windows.Input.MouseWheelController.OnPreviewMouseWheel(Object sender, MouseWheelEventArgs e)
           at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
           at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
           at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
           at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
           at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
           at System.Windows.Input.InputManager.ProcessStagingArea()
           at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
           at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
           at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
           at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
           at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
           at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
           at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
           at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
           at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
           at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
           at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
           at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
           at System.Windows.Application.RunDispatcher(Object ignore)
           at System.Windows.Application.RunInternal(Window window)
           at MarkdownEdit.App.Main() in C:\Users\guban\work\Markdown-Edit\src\MarkdownEdit\obj\Debug\App.g.cs:line 0

**Comment by mike-ward** [comment]
Thanks for the followup.
