### ISSUE TITLE
Changing theme causes crash

### ISSUE THREAD

**Issue by cyotek** [mike-ward/Markdown-Edit#242]
Hello,

The following crash is reported each time I try and configure a theme using MDE on a laptop. Fortunately the setting is saved, but it's 100% reproducible on this laptop. At this point I haven't tested to see if it's also reproducible on my desktop.

```
---------------------------

---------------------------
MarkdownEdit Crash Report

Date: 2017-04-09 10:01:09Z

Version: 1.32



-----------------------------------------------------------------

*** Pressing Ctrl+C will copy the contents of this dialog ***

*** Email to: mike@mike-ward.net ***

-----------------------------------------------------------------



Operation System Information

-----------------------------------------------------------------

Windows 10 Home

Service Pack: No Service Pack detected





Exception

-----------------------------------------------------------------

System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.

   at System.Windows.Threading.Dispatcher.VerifyAccess()

   at MarkdownEdit.Models.Notify.Show(String message, MessageBoxButton button, MessageBoxImage image, Window owner) in C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\Models\Notify.cs:line 0

   at MarkdownEdit.Models.UserSettings.Load() in C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\Models\UserSettings.cs:line 283

   at MarkdownEdit.Models.UserSettings.Update() in C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\Models\UserSettings.cs:line 227

   at MarkdownEdit.Models.FileExtensions.<>c__DisplayClass2_0.<WatchFile>b__0(Object sender, FileSystemEventArgs args) in C:\Users\mike\GitHub\Markdown-Edit\src\MarkdownEdit\Models\FileExtensions.cs:line 50

   at System.IO.FileSystemWatcher.OnChanged(FileSystemEventArgs e)

   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)

   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)

   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)


---------------------------
OK   
---------------------------
```

Thanks;
Richard Moss

**Comment by mike-ward** [comment]
Um... Not seeing this here. Anyone else?

**Comment by cyotek** [comment]
It doesn't repro on my desktop. I fired up the laptop and tried to reproduce - worked fine with several attempts. Next I fired up VS2017 and both VS and Resharper started whining they were out of date, so I initiated their updates. While waiting for that to complete I thought I'd try and repro the crash again - and this time it blew up with the same exception as above. So it definitely happens on at least one of my devices but I don't know the trigger or a solid repro. I'm assuming it was a coincidence re running VS above but the battery on the laptop was almost flat so ended up suspending it while VS was still updating and haven't been able to test further.

**Comment by justdmitry** [comment]
Where are you changing themes? I see folder in file system but does not see any control/combobox in Settings panel ([tall and narrow screenshot](https://user-images.githubusercontent.com/3540597/27958971-2d4ccc3a-632e-11e7-8dde-c639e3707f70.png))

**Comment by mike-ward** [comment]
Ctrl+T

**Comment by justdmitry** [comment]
Wow! Great! Thanks. RTFM indeed :)

About this issue: no crash, works brilliant (Win10 with VS2015, VS2017 and all other .NET dev stuff)

**Comment by mike-ward** [comment]
I'm currently rewriting MDE to use a modern architecture and have decided I need to add something to make these features more discoverable. Not sure what that something is just yet.
